name: main
on:
  push:
  pull-request:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create task in tracker
      run: chmod +x ./.github/task.sh
