name: main
on:
  push:
    tags:
      - '*'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create task in tracker
      run: chmod +x ./.github/task.sh
