name: main
on:
  push:
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: 'setup node'
      with:
        node-version: '14'
        
    - name: Install jq
      run: sudo apt-get install -y jq

    #- name: 'install'
      #run: npm i

    - name: Create task in tracker
      run: sh ./.github/task.sh
      env:
          OAuth: ${{ secrets.OAuth }}
          OrganizationId: ${{ secrets.OrganizationId }}
      
    #- name: 'test'
      #run: npm test
